name: Publish Package

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:  # Manually start a workflow

jobs:
  release-windows:
    runs-on: windows-2016
    env:
      OH_PLATFORM: Windows-x86
      CMAKE_GENERATOR: "Visual Studio 15 2017"
      MSVER: "14.16.27023"
      WKITVER: "10.0.17134.0"
      TOOLSVER: BuildTools
      CXX: ""
      CC: ""
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@master
        with:
          python-version: "3.8"
      - name: Setup msbuild
        uses: microsoft/setup-msbuild@v1.0.3
        with:
          vs-version: '[${{ env.MSVER }}]'
      - name: Generating conan user directory
        run: |
          python --version
          python -m pip install conan==1.33.0 conan_package_tools -U
          conan profile new default --detect
          conan profile update settings.arch=x86 default
          conan profile update settings.compiler.runtime=MT default
          conan user

      - name: Building 
        shell: bash
        run: |
          pip install boto3
          conan install . --build=missing
          git clone https://github.com/merakiacoustic/ohdevtools ../ohdevtools
          ./go fetch ohNet
          mkdir -p dependencies/AnyPlatform
          git clone https://github.com/merakiacoustic/ohWafHelpers.git -b enable-upstream-libressl dependencies/AnyPlatform/ohWafHelpers
          ./waf configure -v
          ./waf build -v
          ./waf bundle
          mv build/ohMediaPlayer.tar.gz build/ohMediaPlayer-$OH_PLATFORM.tar.gz
      - uses: actions/upload-artifact@v2
        name: Upload artifact
        with:
          name: windows
          path: build/ohMediaPlayer-*.tar.gz
